version: "3.7"

services:
  app:
    build: ./
    #ports:
    #  - 8080:80
    volumes:
      - ./src/:/var/app/src
      - ./resources/:/var/app/resources
    command: "php /var/app/src/app.php"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.4
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: "mysqld --init-file /data/application/init.sql"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb

volumes:
  mariadb-data:
